<a href="https://colab.research.google.com/github/saranyaguhanathan/community/blob/main/NUMPYTask2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy_tasks.ipynb_
#Numpy
# 1. Import the numpy package under the name np (★☆☆)
import numpy as np


In [ ]:
# 2. Print the numpy version and the configuration (★☆☆)
print("numpy version:",np.__version__)
print("\n")
print("numpy configuration:",np.show_config())

numpy version: 1.21.6


blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE

In [ ]:
# 3. Create a null vector of size 10 (★☆☆)
import numpy as np
a=np.zeros(10)
print("A null vector in size 10:",a)

 

A null vector in size 10: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# 4. How to find the memory size of any array (★☆☆)
#create a numpy 1-D array
x=np.array([10,20,30,40,50,60])
print(x)
print("Size of the array:",x.size,"\n")
print("Memory size of an element in array in bytes:", x.itemsize,"\n")
print("Memory Size of whole numpy array in  bytes:",(x.size*x.itemsize))


[10 20 30 40 50 60]
Size of the array: 6 

Memory size of an element in array in bytes: 8 

Memory Size of whole numpy array in  bytes: 48


In [ ]:
# 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
print(np.info(np.add))


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [ ]:
# 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
import numpy as np
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# 7. Create a vector with values ranging from 10 to 49 (★☆☆)
v=np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# 8. Reverse a vector (first element becomes last) (★☆☆)
v=np.arange(10,20)
print(v[::-1])


[19 18 17 16 15 14 13 12 11 10]


In [ ]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
m=np.arange(9).reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
non_zero=np.nonzero([1,2,0,0,4,0])
print(non_zero)

(array([0, 1, 4]),)


In [ ]:
# 11. Create a 3x3 identity matrix (★☆☆)
z=np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 12. Create a 3x3x3 array with random values (★☆☆)
a=np.random.uniform((3,3,3))
print(a)


[2.92543307 2.49800747 2.1086236 ]


In [ ]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
a=np.random.uniform((10,10))
print(a)
a_minimum=a.min()
a_maximum=a.max()
print(a_minimum,a_maximum)

[6.36823592 8.74544183]
6.368235920833438 8.745441827730314


In [ ]:
# 14. Create a random vector of size 30 and find the mean value (★☆☆)
a=np.random.random(30)
print(a)
print("MEAN:",a.mean())

[0.21155222 0.47572054 0.44332154 0.4949955  0.94656387 0.82509753
 0.4757226  0.6085358  0.6351597  0.14783549 0.28895511 0.07670737
 0.85628154 0.10301609 0.417846   0.50008545 0.79040241 0.38724534
 0.01020379 0.6461433  0.17809685 0.79691997 0.69277734 0.59038456
 0.72056876 0.54291777 0.82631735 0.71302997 0.87352994 0.16230571]
MEAN: 0.514607979739383


In [ ]:
# 15.Create a 2d array with 1 on the border and 0 inside (★☆☆)
z=np.ones((5,5))
z[1:-1,1:-1]=0
print(z)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
a=np.ones((10,10))
A=np.pad(a,pad_width=1,mode='constant',constant_values=0)
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# 17. What is the result of the following expression? (★☆☆)
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [ ]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
m=np.diag(1+np.arange(4),k=-1)
print(m)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
a=np.zeros((8,8),dtype=int)
a[1::2,::2]=1
a[::2,1::2]=1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
a=np.unravel_index(100,(6,7,8))
print(a)

(1, 5, 4)


In [ ]:
# 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
array=np.array([[0,1],[1,0]])
z=np.tile(array,(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# 22. Normalize a 5x5 random matrix (★☆☆)
mat=np.random.random((5,5))
mat_max=mat.max()
mat_min=mat.min()
mat=mat-mat_min/(mat_max-mat_min)
print(mat)

[[ 0.70238264  0.53231988  0.09547548  0.01412145  0.5986055 ]
 [ 0.66649943  0.38870641  0.34623129  0.68394872 -0.01652322]
 [ 0.15887341  0.36147335  0.37932421  0.37583546  0.53445208]
 [ 0.29903437  0.65416648  0.22969122  0.49078779  0.00081054]
 [ 0.30964703  0.76451614  0.21024677  0.29744318  0.19801677]]


In [ ]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
color=np.dtype([('r',np.ubyte),
                ('g',np.ubyte),
                ('b',np.ubyte),
                ('a',np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [ ]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
DOT=np.dot(np.ones((5,3)),np.ones((3,2)))
print(DOT)
#another method
DOT1=(np.ones((5,3))@np.ones((3,2)))
print(DOT1)


[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [ ]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
a=np.arange(11)
print(a)
a[(3>=a) @ (a<=8)] *= -1
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]
[  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10]


In [ ]:
# 26. What is the output of the following script? (★☆☆)

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [ ]:
# 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
import numpy as np
Z = np.arange(9).reshape(3,3)

print("Z:","\n")
print("Z**Z",Z**Z,"\n")
print("2 << Z >> 2",2 << Z >> 2,"\n")
print("Z <- Z",Z <- Z,"\n")
print("1j*Z",1j*Z,"\n")
print("Z/1/1",Z/1/1,"\n")
print("Z<Z>Z",Z<Z>Z)



Z: 

Z**Z [[       1        1        4]
 [      27      256     3125]
 [   46656   823543 16777216]] 

2 << Z >> 2 [[  0   1   2]
 [  4   8  16]
 [ 32  64 128]] 

Z <- Z [[False False False]
 [False False False]
 [False False False]] 

1j*Z [[0.+0.j 0.+1.j 0.+2.j]
 [0.+3.j 0.+4.j 0.+5.j]
 [0.+6.j 0.+7.j 0.+8.j]] 

Z/1/1 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]] 



ValueError: ignored

In [ ]:
# 28. What are the result of the following expressions?
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

#error explanantion
#print(np.array(0) / np.array(0)) :

#RuntimeWarning: invalid value encountered in true_divide

#print(np.array(0) // np.array(0)) :

#RuntimeWarning: divide by zero encountered in floor_divide

#print(np.array([np.nan]).astype(int).astype(float))


nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
# 29. How to round away from zero a float array ? (★☆☆)

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
#print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[  4.  -9. -10.  -8.   8.   2.  -6.   7.   8.   2.]
[  4.  -9. -10.  -8.   8.   2.  -6.   7.   8.   2.]


In [ ]:
# 30. How to find common values between two arrays? (★☆☆)

Z1 = np.random.randint(0, 15, 10)
Z2 = np.random.randint(0, 15, 10)
print(Z1)
print(Z2)
print(np.intersect1d(Z1, Z2))

[ 3  2  2 11 10 11 13  2  5  8  6]
[ 2  2  4 14  4  3  0 12  7  9]
[2 3]


In [ ]:
# 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

In [ ]:
# 32. Is the following expressions true? (★☆☆)

np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


False

In [ ]:
# 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2022-11-04
2022-11-05
2022-11-06


In [ ]:
# 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
# 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#`hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=)`
A = np.ones(3)*1
B = np.ones(3)*2
l=np.add(A,B,out=B)
m=np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [ ]:
# 36. Extract the integer part of a random array using 5 different methods (★★☆)
# (hint: %, np.floor, np.ceil, astype, np.trunc)

Z = np.random.uniform(0,15,10)
print(Z)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


[ 9.69864845 12.93663405 14.16165008  5.36433776  0.53782287 14.82695064
 14.18741748  6.87818628  1.1213433  13.86828726]
[ 9. 12. 14.  5.  0. 14. 14.  6.  1. 13.]
[ 9. 12. 14.  5.  0. 14. 14.  6.  1. 13.]
[ 9. 12. 14.  5.  0. 14. 14.  6.  1. 13.]
[ 9 12 14  5  0 14 14  6  1 13]
[ 9. 12. 14.  5.  0. 14. 14.  6.  1. 13.]


In [ ]:
# 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
# (hint: np.arange)

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [ ]:
# 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
# (hint: np.fromiter)

def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=int,count=-1)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
# (hint: np.linspace)
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [ ]:
# 40. Create a random vector of size 10 and sort it (★★☆)
Z = np.random.random(10)
print("Before sorting:\n",Z)
Z.sort()
print("After sorting:\n",Z)

Before sorting:
 [0.05800654 0.96053952 0.56525566 0.72906793 0.09540154 0.66983563
 0.33265383 0.24843548 0.98987663 0.59218339]
After sorting:
 [0.05800654 0.09540154 0.24843548 0.33265383 0.56525566 0.59218339
 0.66983563 0.72906793 0.96053952 0.98987663]


In [ ]:
# 41. How to sum a small array faster than np.sum? (★★☆)
Z = np.arange(25)
print(Z)
z=np.add.reduce(Z)
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
300


In [ ]:
# 42. Consider two random array A and B, check if they are equal (★★☆)
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print(A)
print(B)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

[1 0 1 0 1]
[1 0 1 0 1]
True
True


In [ ]:
# 43. Make an array immutable (read-only) (★★☆)
Z = np.zeros(10)
#making array immutable 
Z.flags.writeable = False
#trying change the value
Z[0] = 1

ValueError: ignored

In [ ]:
# 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
# (hint: np.sqrt, np.arctan2)
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


[0.44723531 0.78575748 0.75970405 1.20738826 0.66938993 0.87378526
 0.9510418  1.06130125 0.789538   0.79880047]
[1.11048014 1.04692666 0.31803054 0.81766404 1.4163375  0.2133308
 0.43437971 0.9580928  0.38746148 0.12040774]


In [ ]:
# 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.05289845 0.22022195 0.20140274 0.17069633 0.         0.02278043
 0.67706272 0.84201552 0.23501395 0.5820292 ]


In [ ]:
# 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [ ]:
# 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


In [ ]:
# 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [ ]:
# 49. How to print all the values of an array? (★★☆)
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

76


In [ ]:
# 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


In [ ]:
# 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)

[[0.         0.78710538 0.44619229 0.94138598 0.60857673 0.56461099
  0.951629   0.30137187 0.50723916 0.38001771]
 [0.78710538 0.         0.41315883 0.17313339 0.64859141 0.46001404
  0.27020306 0.59956289 0.35537074 0.73863086]
 [0.44619229 0.41315883 0.         0.53293964 0.66368172 0.16078001
  0.51455673 0.41991238 0.35153991 0.59264197]
 [0.94138598 0.17313339 0.53293964 0.         0.8140239  0.53259562
  0.14879269 0.77067463 0.52849856 0.91173838]
 [0.60857673 0.64859141 0.66368172 0.8140239  0.         0.82070819
  0.91532084 0.31845854 0.33666652 0.26094336]
 [0.56461099 0.46001404 0.16078001 0.53259562 0.82070819 0.
  0.46975418 0.579394   0.49846554 0.75176561]
 [0.951629   0.27020306 0.51455673 0.14879269 0.91532084 0.46975418
  0.         0.82466851 0.60356165 0.97957664]
 [0.30137187 0.59956289 0.41991238 0.77067463 0.31845854 0.579394
  0.82466851 0.         0.25560548 0.17284083]
 [0.50723916 0.35537074 0.35153991 0.52849856 0.33666652 0.49846554
  0.60356165 0.2556054

In [ ]:
# 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)


In [ ]:
# 54. How to read the following file? (★★☆)
#1, 2, 3, 4, 5
#6,  ,  , 7, 8
# ,  , 9,10,11
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if sys.path[0] == '':


In [ ]:
# 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [ ]:
# 56. Generate a generic 2D Gaussian-like array (★★☆)
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [ ]:
# 57. How to randomly place p elements in a 2D array? (★★☆)
n = 10
p = 4
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 2. 0. 0.]
 [2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# 58. Subtract the mean of each row of a matrix (★★☆)
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.14011141  0.55117833 -0.19542834  0.01448326 -0.25746406 -0.09964127
  -0.11029183 -0.07208335 -0.19648328  0.50584195]
 [ 0.11668057 -0.04921867 -0.51313828  0.29765753  0.33325605 -0.4297999
  -0.01595412 -0.1750554   0.34761397  0.08795825]
 [-0.19790095 -0.27641076 -0.09558273 -0.27110779 -0.06113806  0.25942256
   0.58306326  0.28369309  0.00106671 -0.22510534]
 [ 0.20514659 -0.22518669 -0.2361719   0.17011138  0.14067534  0.23459882
  -0.42780286  0.47236403  0.15833513 -0.49206985]
 [ 0.0709731   0.16894631  0.22672264 -0.39982126  0.31204665 -0.40426632
  -0.42569152  0.1165639   0.15576187  0.17876464]]


In [ ]:
# 59. How to sort an array by the nth column? (★★☆)
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,2].argsort()])

[[4 7 9]
 [8 5 7]
 [1 0 8]]
[[8 5 7]
 [1 0 8]
 [4 7 9]]


In [ ]:
# 60. How to tell if a given 2D array has null columns? (★★☆)
# null : 0 
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))

False
[False False  True]


In [ ]:
# 61. Find the nearest value from a given value in an array (★★☆)
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5119751699532196


In [ ]:
# 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
# 63. Create an array class that has a name attribute (★★☆)
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [ ]:
# 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[3. 3. 2. 1. 3. 2. 5. 4. 4. 3.]
[5. 5. 3. 1. 5. 3. 9. 7. 7. 5.]


In [ ]:
# 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [ ]:
# 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)


w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)

64
64


In [ ]:
# 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[[[5 0 7 2]
   [8 9 4 3]
   [5 5 3 9]]

  [[1 0 2 7]
   [7 4 0 6]
   [6 8 5 7]]

  [[9 6 3 4]
   [2 0 1 7]
   [3 8 3 8]]

  [[3 8 7 6]
   [1 2 0 8]
   [5 1 7 5]]]


 [[[0 8 2 0]
   [3 3 8 3]
   [3 6 1 7]]

  [[9 1 2 6]
   [9 3 8 1]
   [6 1 3 9]]

  [[9 7 9 9]
   [5 2 8 0]
   [2 6 4 7]]

  [[9 3 1 9]
   [7 5 9 1]
   [1 2 7 3]]]


 [[[0 4 7 6]
   [6 2 5 3]
   [5 4 7 2]]

  [[5 2 3 3]
   [0 8 5 2]
   [1 6 0 3]]

  [[1 6 2 1]
   [9 7 8 1]
   [7 7 1 2]]

  [[5 4 7 6]
   [9 4 1 0]
   [0 8 6 1]]]]
[[60 53 54 53]
 [44 58 68 57]
 [51 38 52 51]]
[[60 53 54 53]
 [44 58 68 57]
 [51 38 52 51]]


In [ ]:
# 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())


[0.61876649 0.46615256 0.55272648 0.46266977 0.37687673 0.62840178
 0.40011775 0.54360275 0.54038833 0.60152302]
0    0.618766
1    0.466153
2    0.552726
3    0.462670
4    0.376877
5    0.628402
6    0.400118
7    0.543603
8    0.540388
9    0.601523
dtype: float64


In [ ]:
# 69. How to get the diagonal of a dot product? (★★★)
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
x=np.diag(np.dot(A, B))
print(x)

# Fast version
y=np.sum(A * B.T, axis=1)
print(y)

# Faster version
np.einsum("ij,ji->i", A, B)


[1.39776563 2.24623403 0.72466455 0.4138507  0.39933369]
[1.39776563 2.24623403 0.72466455 0.4138507  0.39933369]


array([1.39776563, 2.24623403, 0.72466455, 0.4138507 , 0.39933369])

In [ ]:
# 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [ ]:
# 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [ ]:
# 72. How to swap two rows of an array? (★★★)
A = np.arange(25).reshape(5,5)
print(A)
A[[0,2]] = A[[2,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
# 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)
# `hint: repeat, np.roll, np.sort, view, np.unique`
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 41) ( 0, 56) ( 6, 15) ( 6, 31) ( 6, 72) ( 6, 92) ( 8, 45) ( 8, 54)
 ( 9, 44) ( 9, 61) (15, 92) (16, 93) (16, 96) (18, 56) (18, 95) (22, 47)
 (22, 48) (31, 72) (41, 42) (41, 45) (41, 56) (42, 45) (44, 61) (45, 54)
 (47, 48) (56, 95) (60, 82) (60, 94) (82, 94) (93, 96)]


In [ ]:
# 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
C = np.bincount([1,1,2,3,4,4,6,7])
print(C)
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 2 1 1 2 0 1 1]
[1 1 2 3 4 4 6 7]


In [ ]:
# 75. How to compute averages using a sliding window over an array? (★★★)
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [ ]:
# 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)


Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))




[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
# 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)


array([ 0.57778817, -0.07493025,  0.21597066, -0.89710788,  0.67584288,
       -0.00475281, -0.81357533, -0.51797404,  0.26355306,  0.39721955,
       -0.72405433, -0.54121919, -0.9253865 , -0.73318623,  0.4002081 ,
       -0.22395485, -0.88491913, -0.01353518, -0.9524901 ,  0.93388262,
        0.02340188, -0.24042185, -0.31266013,  0.36145101,  0.02182502,
       -0.72929181, -0.88082246, -0.77517624,  0.08189858, -0.68932182,
        0.77679154, -0.03232339,  0.87185647, -0.93179398,  0.01425635,
       -0.59213185, -0.76156142,  0.94953756, -0.99255633, -0.55498461,
       -0.8967827 ,  0.04813851,  0.25036393, -0.44788473,  0.74477646,
        0.88231202, -0.13014565,  0.94777255, -0.06737853,  0.78187189,
       -0.96134621, -0.02920685, -0.05127693, -0.03547928,  0.02901672,
       -0.51099229, -0.5361018 ,  0.72659053,  0.42243221,  0.79936679,
        0.96462698,  0.39740832, -0.70632645, -0.5839438 , -0.59681127,
        0.59781319,  0.37607826,  0.59587664, -0.24042358, -0.51

In [ ]:
# 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[3.33807026 2.56262571 2.67990634 3.49399537 1.25664095 8.56496712
 4.07104334 6.83179719 1.71381528 3.08743442]


In [ ]:
# 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)
# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.98008208  3.39772795  6.43021223  6.1995822   4.15491818  7.39387284
   8.00477454  3.51826393  3.55393506  4.74116258]
 [ 5.37569169  9.33791505 10.91722304  8.44977506  6.9759483   4.77463061
   6.62814752  2.97314724  1.23123503  0.97674963]
 [ 9.7943492   3.71674019 10.83225008 13.12441784 10.61089796 15.14972796
  16.06877953 11.5800564   3.3164974   8.61746654]
 [ 2.57822665  0.84846362  4.03848346  5.92487994  3.37424775 10.8141313
  10.58410616  5.49402398  3.89189524  9.64853715]
 [ 6.71012577  0.06799027  1.28028133  3.5569147   5.29788932  0.99717266
   1.38423362  6.27832523 13.27828822  2.72312205]
 [ 4.12202724  4.73033579  3.04146281  7.6187641   4.46278272 16.19826647
  15.26847754  9.61321181  2.27250659 15.33074158]
 [ 7.00766544 10.0352921  12.28467967 10.08859343  8.58086382  6.06250722
   8.11068158  4.5438315   0.4043176   0.80284157]
 [ 0.25616694  5.18117431  0.4079994   3.69870936  0.77465484 12.04575714
  10.8886281   5.19607993  6.1659403  13.45949975]
 

In [ ]:
# 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[3 1 2 3 6 5 3 6 2 7]
 [0 1 7 2 9 4 4 0 2 3]
 [3 3 8 1 2 5 0 5 9 2]
 [6 8 0 3 7 4 9 0 4 2]
 [5 2 7 0 2 3 3 3 5 8]
 [2 0 8 5 9 0 0 6 8 6]
 [7 7 3 5 0 1 5 6 8 7]
 [3 9 6 4 5 1 9 4 8 8]
 [3 9 9 0 1 5 9 8 8 9]
 [8 1 0 8 2 3 7 9 7 2]]
[[0 0 0 0 0]
 [0 3 1 2 3]
 [0 0 1 7 2]
 [0 3 3 8 1]
 [0 6 8 0 3]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [ ]:
# 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
Z = np.arange(1,15,dtype=np.uint32)
print(Z)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

# another method
Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [ ]:
# 82. Compute a matrix rank (★★★)
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

# alternative solution:

rank = np.linalg.matrix_rank(Z)
print(rank)

10
10


In [ ]:
# 83. How to find the most frequent value in an array?
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

6


In [ ]:
# 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
Z = np.random.randint(0,5,(10,10))
print(Z)
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

#another method

Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[0 1 1 4 1 1 3 1 3 4]
 [1 2 3 1 3 3 3 0 1 4]
 [3 3 4 2 1 2 1 1 1 2]
 [3 4 1 1 4 2 4 4 1 3]
 [4 2 4 2 1 4 1 0 2 4]
 [0 2 3 0 3 1 0 1 1 3]
 [0 3 4 3 3 4 3 1 3 3]
 [1 4 1 2 0 4 1 0 2 3]
 [2 1 2 3 2 4 1 4 0 2]
 [2 1 3 3 2 0 2 1 2 2]]
[[[[0 1 1]
   [1 2 3]
   [3 3 4]]

  [[1 1 4]
   [2 3 1]
   [3 4 2]]

  [[1 4 1]
   [3 1 3]
   [4 2 1]]

  [[4 1 1]
   [1 3 3]
   [2 1 2]]

  [[1 1 3]
   [3 3 3]
   [1 2 1]]

  [[1 3 1]
   [3 3 0]
   [2 1 1]]

  [[3 1 3]
   [3 0 1]
   [1 1 1]]

  [[1 3 4]
   [0 1 4]
   [1 1 2]]]


 [[[1 2 3]
   [3 3 4]
   [3 4 1]]

  [[2 3 1]
   [3 4 2]
   [4 1 1]]

  [[3 1 3]
   [4 2 1]
   [1 1 4]]

  [[1 3 3]
   [2 1 2]
   [1 4 2]]

  [[3 3 3]
   [1 2 1]
   [4 2 4]]

  [[3 3 0]
   [2 1 1]
   [2 4 4]]

  [[3 0 1]
   [1 1 1]
   [4 4 1]]

  [[0 1 4]
   [1 1 2]
   [4 1 3]]]


 [[[3 3 4]
   [3 4 1]
   [4 2 4]]

  [[3 4 2]
   [4 1 1]
   [2 4 2]]

  [[4 2 1]
   [1 1 4]
   [4 2 1]]

  [[2 1 2]
   [1 4 2]
   [2 1 4]]

  [[1 2 1]
   [4 2 4]
   [1 4 1]]

  [[2 1 1]
   [2 4 4]
   [4 1 

In [ ]:
# 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)


[[ 7  3  5  6  6]
 [ 3  4 12 14 11]
 [ 5 12  2 42  7]
 [ 6 14 42  7 10]
 [ 6 11  7 10  8]]


In [ ]:
# 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [ ]:
# 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

# alternative solution:

Z = np.ones((16,16))
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))


Z = np.ones((16, 16))
k = 4
print(sliding_window_view(Z, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [ ]:
# 88. How to implement the Game of Life using numpy arrays? (★★★)
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0
  1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 1
  1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0

In [ ]:
# 89. How to get the n largest values of an array (★★★)
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


In [ ]:
# 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [ ]:
# 91. How to create a record array from a regular array? (★★★)
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)


[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [ ]:
# 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.74 s ± 21.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
135 ms ± 1.01 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
114 ms ± 1.06 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
# 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 3 4 5 6 7]


In [ ]:
# 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 1 0]
 [3 3 4]
 [2 2 0]
 [2 0 3]
 [1 4 2]
 [2 0 3]
 [3 1 4]
 [3 1 4]
 [3 1 0]
 [1 0 0]]
[[4 1 0]
 [3 3 4]
 [2 2 0]
 [2 0 3]
 [1 4 2]
 [2 0 3]
 [3 1 4]
 [3 1 4]
 [3 1 0]
 [1 0 0]]
[[4 1 0]
 [3 3 4]
 [2 2 0]
 [2 0 3]
 [1 4 2]
 [2 0 3]
 [3 1 4]
 [3 1 4]
 [3 1 0]
 [1 0 0]]


In [151]:
# 95. Convert a vector of ints into a matrix binary representation (★★★)
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author method

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [152]:
# 96. Given a two dimensional array, how to extract unique rows? (★★★)
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [1 1 0]
 [1 1 1]]
[[0 0 0]
 [1 1 0]
 [1 1 1]]


In [153]:
# 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.67209011, 0.17629428, 0.512293  , 0.23242148, 0.22384264,
        0.89943195, 0.29241339, 0.69664781, 0.33229381, 0.62528828],
       [0.42488706, 0.11145107, 0.32386531, 0.14693399, 0.14151055,
        0.56860977, 0.18486013, 0.44041214, 0.21007204, 0.39529953],
       [0.57867735, 0.15179141, 0.44109019, 0.20011758, 0.1927311 ,
        0.7744213 , 0.25177131, 0.59982182, 0.28610881, 0.53838044],
       [0.22022006, 0.05776538, 0.16786023, 0.07615627, 0.07334528,
        0.29471191, 0.09581348, 0.22826675, 0.10888088, 0.20488477],
       [0.10254444, 0.02689818, 0.07816333, 0.03546181, 0.03415289,
        0.13723122, 0.0446151 , 0.10629135, 0.05069987, 0.09540363],
       [0.67062853, 0.1759109 , 0.51117893, 0.23191604, 0.22335585,
        0.89747598, 0.29177749, 0.69513283, 0.33157118, 0.62392849],
       [0.34597394, 0.09075156, 0.26371468, 0.11964434, 0.11522818,
        0.46300341, 0.15052656, 0.35861559, 0.17105593, 0.32188162],
       [0.61583921, 0.16153925, 0.4694163

In [158]:
# 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [156]:
# 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [157]:
# 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.18050547  0.19806137]
